### ISSUE TITLE
Address and code of deployed FiatToken contract

### ISSUE THREAD

**Issue by asymmetric** [centrehq/centre-tokens#233]
Hi,

I was searching for a "verified" `FiatToken` contract on etherscan, and couldn't find any.

Your website points to [0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48](https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48), which seems to be the `Proxy` contract.

I also searched through the transactions made by the [deployer](https://etherscan.io/address/0x95ba4cf87d6723ad9c0db21737d862be80e93911), but couldn't find a deployment of `FiatToken`.

**Comment by eztierney** [comment]
The FiatToken is deployed at 
[0x0882477e7895bdc5cea7cb1552ed914ab157fe56](https://etherscan.io/address/0x0882477e7895bdc5cea7cb1552ed914ab157fe56)

You can verify this is the implementation by calling 
```
eth.getStorageAt(proxyAddress, '0x7050c9e0f4ca769c69bd3a8ef740bc37934f8e2c036e5a723fd8ee048ed3f8c3');
```
from the console.
