### ISSUE TITLE
Upgrade to ERC865?

### ISSUE THREAD

**Issue by aunyks** [centrehq/centre-tokens#236]
Are there any considerations of having `FiatTokenV3` be [ERC865](https://github.com/ethereum/EIPs/issues/865)-compatible? I think it would provide a significant boost to UX if members of the CENTRE ecosystem could allow users to pay fees in USDC in a chain-native manner when applicable.  

I'd be happy to lead the effort if possible.

**Comment by eztierney** [comment]
We don't have any plans to add support for ERC865 at this time, but we would look into it as is moves through the standards process. It would be cool for users to be able to use USDC without ever needing ETH for gas.

Always happy for PRs, even if it would likely be a while before we were ready to integrate it.

**Comment by aunyks** [comment]
Interesting. I might open a PR in the future
