### ISSUE TITLE
View methods in the proxy contract cannot be read by a non admin.

### ISSUE THREAD

**Issue by bejavu** [centrehq/centre-tokens#238]
The proxy contract (the erc20 address) do not show the admin and implementation values in read contract tab of etherscan:

https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48#readContract

This is because of the `ifAsmin` modifier:

```solidity
function admin() external view ifAdmin returns (address) {
  return _admin();
}

modifier ifAdmin() {
  if (msg.sender == _admin()) {
    _;
  } else {
    _fallback();
  }
}
```

**Comment by eztierney** [comment]
Yes this is a limitation of the current implementation. 
As a workaround you can check the values using `getStorageAt` from the console:

```
// admin
eth.getStorageAt(proxyAddress, 0x10d6a54a4754c8869d6886b5f5d7fbfa5b4522237ea5c60d11bc4e7a1ff9390b)

// implementation
eth.getStorageAt(proxyAddress, 0x7050c9e0f4ca769c69bd3a8ef740bc37934f8e2c036e5a723fd8ee048ed3f8c3)
```

**Comment by sayyankhonkhaeng** [comment]
// admin
eth.getStorageAt(proxyAddress, 0x10d6a54a4754c8869d6886b5f5d7fbfa5b4522237ea5c60d11bc4e7a1ff9390b)

// implementation
eth.getStorageAt(proxyAddress, 0x7050c9e0f4ca769c69bd3a8ef740bc37934f8e2c036e5a723fd8ee048ed3f8c3)

**Comment by petejkim** [comment]
@eztierney close this issue?
