### ISSUE TITLE
make  controllers. minterManager private and create getter functions

### ISSUE THREAD

**Issue by eztierney** [centrehq/centre-tokens#262]
Consider restricting the visibility of the controllers and minterManager variables to internal or private and providing the required getter functions as a good encapsulation practice.

**Comment by mgrissa** [comment]
The compiler already provides getters for these variables, will making them internal and creating public getters make any difference @mirathewhite ?

**Comment by mirathewhite** [comment]
https://github.com/centrehq/centre-tokens/pull/277
