### ISSUE TITLE
Fail to send USDC web3

### ISSUE THREAD

**Issue by supportcoinsafer** [centrehq/centre-tokens#285]
Hi

I'm trying to send USDC as the same way that I'm doing with BNB and TUSD. But the transactions fails, anybody here can help me? I'm using the same ABI for all of them.

https://etherscan.io/tx/0xc2cdc9d93d5ca1926f78e2d7c46d31f181b3a5bb79397bd659df247ec7776ba0

https://etherscan.io/tx/0xbe8a3cdca33370153de9bba5abbfcbb9a2ff5a9f8a18b302b79abf316457f713

https://etherscan.io/tx/0xec33f5fba3357cf90546475277fb906da0d89f032377c9f47bfefe43d90244e0

https://etherscan.io/tx/0x3706978515b0949b99594ab413caec73f07dae1d8784ad4795e8fb7ea2658d2f

async function send(recipientAddress, amount, privateKey) {
const data = contract.methods.transfer(recipientAddress, web3.utils.toWei(amount)).encodeABI();
const wallet = new ethers.Wallet(privateKey, provider);
const transaction = {
gasPrice: web3.eth.gasPrice,
gasLimit: 90000,
to: contractAddress,
data,
};

const transactionHash = await wallet.sendTransaction(transaction);
transactionHash.tx = transactionHash.hash
return transactionHash;

}

**Comment by eztierney** [comment]
I think it is because of the `web3.utils.toWei(amount)` call. USDC only uses 6 decimal places, instead of 18 like BNB and TUSD. You can probably use `web3.utils.toWei(amount, 'mwei')` instead.

**Comment by supportcoinsafer** [comment]
I was believing that you found my solution, but not :( same problem

https://etherscan.io/tx/0x556090b3daad1aae4caf6766e882ff83f53b1baf2030cf24280d27e8bc1853ef

const data = contract.methods.transfer(recipientAddress, web3.utils.toWei(amount, 'mwei')).encodeABI();

Did you this before with USDC? Coud you share your code?

**Comment by supportcoinsafer** [comment]
You was right, I was sending big amount. Tnk you.

**Comment by Amit-codezeros** [comment]
Can you provide ABI code for USDC contract ?
