### ISSUE TITLE
“Approve USDC spend limit” call

### ISSUE THREAD

**Issue by almccann** [centrehq/centre-tokens#313]
What is the purpose of the “Approve USDC spend limit” call? Does it make this call once per account per recipient account?

**Comment by wildwes357** [comment]
> What is the purpose of the “Approve USDC spend limit” call? Does it make this call once per account per recipient account?

Sorry I missed your reply take the truth I can't remember for 21 days ago obviously I think I figured it out, Have a good day sir thank you￼￼
