### ISSUE TITLE
bug in AdminUpgradeabilityProxy.sol

### ISSUE THREAD

**Issue by acvrp-lab** [centrehq/centre-tokens#315]
/**
   * @dev Upgrade the backing implementation of the proxy and call a function
   * on the new implementation.
   */
  function upgradeToAndCall(address newImplementation, bytes data) payable external ifAdmin {
    _upgradeTo(newImplementation);
    require(address(this).call.value(msg.value)(data));
  }

as i just checked openzepplin's latest code,
there's bug in last line, it should be newImplementation instead of address(this)
you code will call

function _willFallback() internal {
    require(msg.sender != _admin(), "Cannot call fallback function from the proxy admin");
    super._willFallback();
  }

which will throw since msg.sender is admin

**Comment by doreetz** [comment]
is this to do with rescueERC20?
